import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MouseTracker } from '@/components/MouseTracker';
import Header from "@/components/Header";
import { ParticlesComponent } from "@/components/ParticlesComponent";
import CanvasCursor from "@/components/CanvasCursor";
import GlassFooter from "@/components/GlassFooter";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased 
          sm:pl-20 sm:pr-20 sm:pt-10 sm:pb-20
          px-4 py-4
        `}
      > 
      <ThemeProvider enableSystem={true} defaultTheme="dark">
        <ParticlesComponent/>
        <Header />
        {children}
        <CanvasCursor/>
        <GlassFooter/>
      </ThemeProvider>
      </body>
    </html>
  );
}
